export const BOOK_COVERS: Record<string, Record<string, string>> = {
  "Class 11-12": {
    "english for today": "/assets/book-covers-extracted/Class 11-12/English Version/English For Today.png"
  },
  "Class 6": {
    "english for today (english 1st paper)": "/assets/book-covers-extracted/Class 6/English Version/English For Today (English 1st Paper).png",
    "english for today": "/assets/book-covers-extracted/Class 6/English Version/English For Today (English 1st Paper).png",
    "english grammar and composition (english 2nd paper)": "/assets/book-covers-extracted/Class 6/English Version/English Grammar and Composition (English 2nd Paper).png",
    "english grammar and composition": "/assets/book-covers-extracted/Class 6/English Version/English Grammar and Composition (English 2nd Paper).png",
    "আনন্দপাঠ": "/assets/book-covers-extracted/Class 6/English Version/আনন্দপাঠ.png",
    "ইসলাম ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 6/Bangla Version/ইসলাম ও নৈতিক শিক্ষা.png",
    "কৃষিশিক্ষা": "/assets/book-covers-extracted/Class 6/Bangla Version/কৃষিশিক্ষা.png",
    "খ্রিষ্টধর্ম  ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 6/Bangla Version/খ্রিষ্টধর্ম  ও নৈতিক শিক্ষা.png",
    "খ্রিষ্টধর্ম ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 6/Bangla Version/খ্রিষ্টধর্ম  ও নৈতিক শিক্ষা.png",
    "গণিত": "/assets/book-covers-extracted/Class 6/Bangla Version/গণিত.png",
    "গার্হস্থ্য বিজ্ঞান": "/assets/book-covers-extracted/Class 6/Bangla Version/গার্হস্থ্য বিজ্ঞান.png",
    "চারুপাঠ (বাংলা ১ম পত্র)": "/assets/book-covers-extracted/Class 6/English Version/চারুপাঠ (বাংলা ১ম পত্র).png",
    "চারুপাঠ": "/assets/book-covers-extracted/Class 6/English Version/চারুপাঠ (বাংলা ১ম পত্র).png",
    "তথ্য ও যোগাযোগ প্রযুক্তি": "/assets/book-covers-extracted/Class 6/Bangla Version/তথ্য ও যোগাযোগ প্রযুক্তি.png",
    "বাংলা ব্যাকরণ ও নির্মিতি (বাংলা ২য় পত্র)": "/assets/book-covers-extracted/Class 6/English Version/বাংলা ব্যাকরণ ও নির্মিতি (বাংলা ২য় পত্র).png",
    "বাংলা ব্যাকরণ ও নির্মিতি": "/assets/book-covers-extracted/Class 6/English Version/বাংলা ব্যাকরণ ও নির্মিতি (বাংলা ২য় পত্র).png",
    "বাংলাদেশ ও বিশ্বপরিচয়": "/assets/book-covers-extracted/Class 6/Bangla Version/বাংলাদেশ ও বিশ্বপরিচয়.png",
    "বিজ্ঞান": "/assets/book-covers-extracted/Class 6/Bangla Version/বিজ্ঞান.png",
    "বৌদ্ধধর্ম  ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 6/Bangla Version/বৌদ্ধধর্ম  ও নৈতিক শিক্ষা.png",
    "বৌদ্ধধর্ম ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 6/Bangla Version/বৌদ্ধধর্ম  ও নৈতিক শিক্ষা.png",
    "হিন্দুধর্ম  ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 6/Bangla Version/হিন্দুধর্ম  ও নৈতিক শিক্ষা.png",
    "হিন্দুধর্ম ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 6/Bangla Version/হিন্দুধর্ম  ও নৈতিক শিক্ষা.png",
    "agriculture studies": "/assets/book-covers-extracted/Class 6/English Version/Agriculture Studies.png",
    "bangladesh and global studies": "/assets/book-covers-extracted/Class 6/English Version/Bangladesh and Global Studies.png",
    "buddhist religion and moral education": "/assets/book-covers-extracted/Class 6/English Version/Buddhist Religion and Moral Education.png",
    "christian religion and moral education": "/assets/book-covers-extracted/Class 6/English Version/Christian Religion and Moral Education.png",
    "hindu religion and moral education": "/assets/book-covers-extracted/Class 6/English Version/Hindu Religion and Moral Education.png",
    "home science": "/assets/book-covers-extracted/Class 6/English Version/Home Science.png",
    "information and commution technology": "/assets/book-covers-extracted/Class 6/English Version/Information and Commution Technology.png",
    "islam and moral education": "/assets/book-covers-extracted/Class 6/English Version/Islam and Moral Education.png",
    "mathematics": "/assets/book-covers-extracted/Class 6/English Version/Mathematics.png",
    "science": "/assets/book-covers-extracted/Class 6/English Version/Science.png"
  },
  "Class 7": {
    "english for today (english 1st paper)": "/assets/book-covers-extracted/Class 7/English Version/English For Today (English 1st Paper).png",
    "english for today": "/assets/book-covers-extracted/Class 7/English Version/English For Today (English 1st Paper).png",
    "english grammar and composition (english 2nd paper)": "/assets/book-covers-extracted/Class 7/English Version/English Grammar and Composition (English 2nd Paper).png",
    "english grammar and composition": "/assets/book-covers-extracted/Class 7/English Version/English Grammar and Composition (English 2nd Paper).png",
    "আনন্দপাঠ": "/assets/book-covers-extracted/Class 7/English Version/আনন্দপাঠ.png",
    "ইসলাম ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 7/Bangla Version/ইসলাম ও নৈতিক শিক্ষা.png",
    "কৃষিশিক্ষা": "/assets/book-covers-extracted/Class 7/Bangla Version/কৃষিশিক্ষা.png",
    "খ্রিষ্টধর্ম  ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 7/Bangla Version/খ্রিষ্টধর্ম  ও নৈতিক শিক্ষা.png",
    "খ্রিষ্টধর্ম ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 7/Bangla Version/খ্রিষ্টধর্ম  ও নৈতিক শিক্ষা.png",
    "গণিত": "/assets/book-covers-extracted/Class 7/Bangla Version/গণিত.png",
    "গার্হস্থ্য বিজ্ঞান": "/assets/book-covers-extracted/Class 7/Bangla Version/গার্হস্থ্য বিজ্ঞান.png",
    "তথ্য ও যোগাযোগ প্রযুক্তি": "/assets/book-covers-extracted/Class 7/Bangla Version/তথ্য ও যোগাযোগ প্রযুক্তি.png",
    "বাংলা ব্যাকরণ ও নির্মিতি (বাংলা ২য় পত্র)": "/assets/book-covers-extracted/Class 7/English Version/বাংলা ব্যাকরণ ও নির্মিতি (বাংলা ২য় পত্র).png",
    "বাংলা ব্যাকরণ ও নির্মিতি": "/assets/book-covers-extracted/Class 7/English Version/বাংলা ব্যাকরণ ও নির্মিতি (বাংলা ২য় পত্র).png",
    "বাংলাদেশ ও বিশ্বপরিচয়": "/assets/book-covers-extracted/Class 7/Bangla Version/বাংলাদেশ ও বিশ্বপরিচয়.png",
    "বিজ্ঞান": "/assets/book-covers-extracted/Class 7/Bangla Version/বিজ্ঞান.png",
    "বৌদ্ধধর্ম  ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 7/Bangla Version/বৌদ্ধধর্ম  ও নৈতিক শিক্ষা.png",
    "বৌদ্ধধর্ম ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 7/Bangla Version/বৌদ্ধধর্ম  ও নৈতিক শিক্ষা.png",
    "সপ্তবর্ণ (বাংলা ১ম পত্র)": "/assets/book-covers-extracted/Class 7/English Version/সপ্তবর্ণ (বাংলা ১ম পত্র).png",
    "সপ্তবর্ণ": "/assets/book-covers-extracted/Class 7/English Version/সপ্তবর্ণ (বাংলা ১ম পত্র).png",
    "হিন্দুধর্ম  ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 7/Bangla Version/হিন্দুধর্ম  ও নৈতিক শিক্ষা.png",
    "হিন্দুধর্ম ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 7/Bangla Version/হিন্দুধর্ম  ও নৈতিক শিক্ষা.png",
    "bangladesh and global studies": "/assets/book-covers-extracted/Class 7/English Version/Bangladesh and Global Studies.png",
    "buddhist religion and moral education": "/assets/book-covers-extracted/Class 7/English Version/Buddhist Religion and Moral Education.png",
    "christian religion and moral education": "/assets/book-covers-extracted/Class 7/English Version/Christian Religion and Moral Education.png",
    "hindu religion and moral education": "/assets/book-covers-extracted/Class 7/English Version/Hindu Religion and Moral Education.png",
    "home science": "/assets/book-covers-extracted/Class 7/English Version/Home Science.png",
    "information and commution technology": "/assets/book-covers-extracted/Class 7/English Version/Information and Commution Technology.png",
    "islam and moral education": "/assets/book-covers-extracted/Class 7/English Version/Islam and Moral Education.png",
    "mathematics": "/assets/book-covers-extracted/Class 7/English Version/Mathematics.png",
    "science": "/assets/book-covers-extracted/Class 7/English Version/Science.png"
  },
  "Class 8": {
    "english for today (english 1st paper)": "/assets/book-covers-extracted/Class 8/English Version/English For Today (English 1st Paper).png",
    "english for today": "/assets/book-covers-extracted/Class 8/English Version/English For Today (English 1st Paper).png",
    "english grammar and composition (english 2nd paper)": "/assets/book-covers-extracted/Class 8/English Version/English Grammar and Composition (English 2nd Paper).png",
    "english grammar and composition": "/assets/book-covers-extracted/Class 8/English Version/English Grammar and Composition (English 2nd Paper).png",
    "আনন্দপাঠ": "/assets/book-covers-extracted/Class 8/English Version/আনন্দপাঠ.png",
    "ইসলাম ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 8/Bangla Version/ইসলাম ও নৈতিক শিক্ষা.png",
    "কৃষিশিক্ষা": "/assets/book-covers-extracted/Class 8/Bangla Version/কৃষিশিক্ষা.png",
    "খ্রিষ্টধর্ম  ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 8/Bangla Version/খ্রিষ্টধর্ম  ও নৈতিক শিক্ষা.png",
    "খ্রিষ্টধর্ম ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 8/Bangla Version/খ্রিষ্টধর্ম  ও নৈতিক শিক্ষা.png",
    "গণিত": "/assets/book-covers-extracted/Class 8/Bangla Version/গণিত.png",
    "গার্হস্থ্য বিজ্ঞান": "/assets/book-covers-extracted/Class 8/Bangla Version/গার্হস্থ্য বিজ্ঞান.png",
    "তথ্য ও যোগাযোগ প্রযুক্তি": "/assets/book-covers-extracted/Class 8/Bangla Version/তথ্য ও যোগাযোগ প্রযুক্তি.png",
    "বাংলা ব্যাকরণ ও নির্মিতি (বাংলা ২য় পত্র)": "/assets/book-covers-extracted/Class 8/English Version/বাংলা ব্যাকরণ ও নির্মিতি (বাংলা ২য় পত্র).png",
    "বাংলা ব্যাকরণ ও নির্মিতি": "/assets/book-covers-extracted/Class 8/English Version/বাংলা ব্যাকরণ ও নির্মিতি (বাংলা ২য় পত্র).png",
    "বাংলাদেশ ও বিশ্বপরিচয়": "/assets/book-covers-extracted/Class 8/Bangla Version/বাংলাদেশ ও বিশ্বপরিচয়.png",
    "বিজ্ঞান": "/assets/book-covers-extracted/Class 8/Bangla Version/বিজ্ঞান.png",
    "বৌদ্ধধর্ম  ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 8/Bangla Version/বৌদ্ধধর্ম  ও নৈতিক শিক্ষা.png",
    "বৌদ্ধধর্ম ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 8/Bangla Version/বৌদ্ধধর্ম  ও নৈতিক শিক্ষা.png",
    "সাহিত্য কণিকা (বাংলা ১ম পত্র)": "/assets/book-covers-extracted/Class 8/English Version/সাহিত্য কণিকা (বাংলা ১ম পত্র).png",
    "সাহিত্য কণিকা": "/assets/book-covers-extracted/Class 8/English Version/সাহিত্য কণিকা (বাংলা ১ম পত্র).png",
    "হিন্দুধর্ম  ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 8/Bangla Version/হিন্দুধর্ম  ও নৈতিক শিক্ষা.png",
    "হিন্দুধর্ম ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 8/Bangla Version/হিন্দুধর্ম  ও নৈতিক শিক্ষা.png",
    "agriculture studies": "/assets/book-covers-extracted/Class 8/English Version/Agriculture Studies.png",
    "bangladesh and global studies": "/assets/book-covers-extracted/Class 8/English Version/Bangladesh and Global Studies.png",
    "buddhist religion and moral education": "/assets/book-covers-extracted/Class 8/English Version/Buddhist Religion and Moral Education.png",
    "christian religion and moral education": "/assets/book-covers-extracted/Class 8/English Version/Christian Religion and Moral Education.png",
    "hindu religion and moral education": "/assets/book-covers-extracted/Class 8/English Version/Hindu Religion and Moral Education.png",
    "home science": "/assets/book-covers-extracted/Class 8/English Version/Home Science.png",
    "information and commution technology": "/assets/book-covers-extracted/Class 8/English Version/Information and Commution Technology.png",
    "islam and moral education": "/assets/book-covers-extracted/Class 8/English Version/Islam and Moral Education.png",
    "mathematics": "/assets/book-covers-extracted/Class 8/English Version/Mathematics.png",
    "science": "/assets/book-covers-extracted/Class 8/English Version/Science.png"
  },
  "Class 9-10": {
    "english for today (english 1st paper)": "/assets/book-covers-extracted/Class 9-10/English Version/English For Today (English 1st Paper).png",
    "english for today": "/assets/book-covers-extracted/Class 9-10/English Version/English For Today (English 1st Paper).png",
    "enlish grammer and composition": "/assets/book-covers-extracted/Class 9-10/English Version/Enlish Grammer and Composition.png",
    "অর্থনীতি": "/assets/book-covers-extracted/Class 9-10/Bangla Version/অর্থনীতি.png",
    "ইসলাম ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 9-10/Bangla Version/ইসলাম ও নৈতিক শিক্ষা.png",
    "উচ্চতর গণিত": "/assets/book-covers-extracted/Class 9-10/Bangla Version/উচ্চতর গণিত.png",
    "কৃষিশিক্ষা": "/assets/book-covers-extracted/Class 9-10/Bangla Version/কৃষিশিক্ষা.png",
    "খ্রিষ্টধর্ম ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 9-10/Bangla Version/খ্রিষ্টধর্ম ও নৈতিক শিক্ষা.png",
    "গণিত": "/assets/book-covers-extracted/Class 9-10/Bangla Version/গণিত.png",
    "গার্হস্থ্য বিজ্ঞান": "/assets/book-covers-extracted/Class 9-10/Bangla Version/গার্হস্থ্য বিজ্ঞান.png",
    "জীববিজ্ঞান": "/assets/book-covers-extracted/Class 9-10/Bangla Version/জীববিজ্ঞান.png",
    "তথ্য ও যোগাযোগ প্রযুক্তি": "/assets/book-covers-extracted/Class 9-10/Bangla Version/তথ্য ও যোগাযোগ প্রযুক্তি.png",
    "পদার্থবিজ্ঞান": "/assets/book-covers-extracted/Class 9-10/Bangla Version/পদার্থবিজ্ঞান.png",
    "পৌরনীতি ও নাগরিকতা": "/assets/book-covers-extracted/Class 9-10/Bangla Version/পৌরনীতি ও নাগরিকতা.png",
    "ফিন্যান্স ও ব্যাংকিং": "/assets/book-covers-extracted/Class 9-10/Bangla Version/ফিন্যান্স ও ব্যাংকিং.png",
    "বাংলা ভাষার ব্যাকরণ (বাংলা ২য় পত্র)": "/assets/book-covers-extracted/Class 9-10/Bangla Version/বাংলা ভাষার ব্যাকরণ (বাংলা ২য় পত্র).png",
    "বাংলা ভাষার ব্যাকরণ": "/assets/book-covers-extracted/Class 9-10/Bangla Version/বাংলা ভাষার ব্যাকরণ (বাংলা ২য় পত্র).png",
    "বাংলা সহপাঠ": "/assets/book-covers-extracted/Class 9-10/English Version/বাংলা সহপাঠ.png",
    "বাংলা সাহিত্য (বাংলা ১ম পত্র)": "/assets/book-covers-extracted/Class 9-10/English Version/বাংলা সাহিত্য (বাংলা ১ম পত্র).png",
    "বাংলা সাহিত্য": "/assets/book-covers-extracted/Class 9-10/English Version/বাংলা সাহিত্য (বাংলা ১ম পত্র).png",
    "বাংলাদেশের ইতিহাস ও বিশ্বসভ্যতা": "/assets/book-covers-extracted/Class 9-10/Bangla Version/বাংলাদেশের ইতিহাস ও বিশ্বসভ্যতা.png",
    "বিজ্ঞান": "/assets/book-covers-extracted/Class 9-10/Bangla Version/বিজ্ঞান.png",
    "বৌদ্ধধর্ম  ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 9-10/Bangla Version/বৌদ্ধধর্ম  ও নৈতিক শিক্ষা.png",
    "বৌদ্ধধর্ম ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 9-10/Bangla Version/বৌদ্ধধর্ম  ও নৈতিক শিক্ষা.png",
    "ব্যবসায় উদ্যোগ": "/assets/book-covers-extracted/Class 9-10/Bangla Version/ব্যবসায় উদ্যোগ.png",
    "ভূগোল ও পরিবেশ": "/assets/book-covers-extracted/Class 9-10/Bangla Version/ভূগোল ও পরিবেশ.png",
    "রচনাসম্ভার": "/assets/book-covers-extracted/Class 9-10/English Version/রচনাসম্ভার.png",
    "রসায়ন": "/assets/book-covers-extracted/Class 9-10/Bangla Version/রসায়ন.png",
    "হিন্দুধর্ম  ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 9-10/Bangla Version/হিন্দুধর্ম  ও নৈতিক শিক্ষা.png",
    "হিন্দুধর্ম ও নৈতিক শিক্ষা": "/assets/book-covers-extracted/Class 9-10/Bangla Version/হিন্দুধর্ম  ও নৈতিক শিক্ষা.png",
    "হিসাববিজ্ঞান": "/assets/book-covers-extracted/Class 9-10/Bangla Version/হিসাববিজ্ঞান.png",
    "accounting": "/assets/book-covers-extracted/Class 9-10/English Version/Accounting.png",
    "agriculture studies": "/assets/book-covers-extracted/Class 9-10/English Version/Agriculture Studies.png",
    "biology": "/assets/book-covers-extracted/Class 9-10/English Version/Biology.png",
    "buddhist religion and moral education": "/assets/book-covers-extracted/Class 9-10/English Version/Buddhist Religion and Moral Education.png",
    "business entrepreneurship": "/assets/book-covers-extracted/Class 9-10/English Version/Business Entrepreneurship.png",
    "chemistry": "/assets/book-covers-extracted/Class 9-10/English Version/Chemistry.png",
    "christian religion and moral education": "/assets/book-covers-extracted/Class 9-10/English Version/Christian Religion and Moral Education.png",
    "civics and citizenship": "/assets/book-covers-extracted/Class 9-10/English Version/Civics and Citizenship.png",
    "economices": "/assets/book-covers-extracted/Class 9-10/English Version/Economices.png",
    "finance and banking": "/assets/book-covers-extracted/Class 9-10/English Version/Finance and Banking.png",
    "geography and environment": "/assets/book-covers-extracted/Class 9-10/English Version/Geography and Environment.png",
    "higher mathematics": "/assets/book-covers-extracted/Class 9-10/English Version/Higher Mathematics.png",
    "hindu religion and moral education": "/assets/book-covers-extracted/Class 9-10/English Version/Hindu Religion and Moral Education.png",
    "history of bangladesh and world civilization": "/assets/book-covers-extracted/Class 9-10/English Version/History of Bangladesh and World Civilization.png",
    "home science": "/assets/book-covers-extracted/Class 9-10/English Version/Home Science.png",
    "information and commution technology": "/assets/book-covers-extracted/Class 9-10/English Version/Information and Commution Technology.png",
    "islam and moral education": "/assets/book-covers-extracted/Class 9-10/English Version/Islam and Moral Education.png",
    "mathematics": "/assets/book-covers-extracted/Class 9-10/English Version/Mathematics.png",
    "physics": "/assets/book-covers-extracted/Class 9-10/English Version/Physics.png"
  }
};
